spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: i8tu6uZD_123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  application:
    name: IDENTITY-SERVICE

server:
  port: 9898

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/